import { Product } from '../product'; // Import the Product type from the 'product' module

// Define a list of products with their specifications
const products: Product[] = [
    {
        id: 1,
        name: 'Acer Nitro 5 Gaming Laptop',
        description:
            'The Acer Nitro 5 is a powerful gaming laptop, ideal for heavy gaming and multitasking.',
        brand: 'Acer',
        model: 'AN515-54-58CL',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Facer-nitro-5.png?alt=media&token=094ba6a8-1a4d-414a-b32c-c176bfeaca8e',
        rating: 4.5,
        videoReview: 'https://www.youtube.com/embed/8NQFr9De3lU?si=s_lN2KTQresD-36Y',
        tags: ['Discounted'],
        basePrice: 6499.99,
        promotionalPrice: 5999.99,
        lowestPrice: 4850.9,
        highestPrice: 9800.8,
        averagePrice: 6503.7,
        specifications: {
            highlight: 'NVIDIA GeForce RTX 2060',
            Processor: 'Intel Core i5-9300H',
            Memory: '16GB DDR4',
            Storage: '512GB SSD',
            'Graphics Card': 'NVIDIA GeForce RTX 2060',
            Screen: '15.6 inches Full HD',
            Weight: '2.5 Kg',
        },
    },
    {
        id: 2,
        name: 'Dell G5 Gaming Laptop',
        description: 'The Dell G5 offers smooth gaming experience and high-quality graphics.',
        brand: 'Dell',
        model: 'G5-5590-A30B',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fdell-g5.png?alt=media&token=ac1cb3fa-4cc4-4f30-a831-19bca5b85644',
        rating: 5,
        videoReview: 'https://www.youtube.com/embed/N5C1ALQkv1Q?si=KuVr4V6-A02Z23XK',
        tags: [],
        basePrice: 7299.99,
        promotionalPrice: 6799.99,
        lowestPrice: 4850,
        highestPrice: 9800,
        averagePrice: 6500,
        specifications: {
            highlight: 'NVIDIA GeForce GTX 1660 Ti',
            Processor: 'Intel Core i7-9750H',
            Memory: '16GB DDR4',
            Storage: '1TB HDD + 256GB SSD',
            'Graphics Card': 'NVIDIA GeForce GTX 1660 Ti',
            Screen: '15.6 inches Full HD',
            Weight: '2.68 Kg',
        },
    },
    {
        id: 3,
        name: 'Lenovo Legion Y540 Gaming Laptop',
        description:
            'The Lenovo Legion Y540 is a high-performance gaming laptop with a sleek design.',
        brand: 'Lenovo',
        model: 'Legion Y540-15IRH',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Flegion-y540.png?alt=media&token=b36f6c61-8b7d-4454-9940-d945b89d44f8',
        rating: 4.5,
        videoReview: 'https://www.youtube.com/embed/knhriyVTMpA?si=3RduZcEVx4mjEwER',
        tags: ['Recommended'],
        basePrice: 6999.99,
        promotionalPrice: 6499.99,
        lowestPrice: 4850,
        highestPrice: 9800,
        averagePrice: 6500,
        specifications: {
            highlight: 'NVIDIA GeForce GTX 1660 Ti',
            Processor: 'Intel Core i7-9750H',
            Memory: '16GB DDR4',
            Storage: '512GB SSD',
            'Graphics Card': 'NVIDIA GeForce GTX 1660 Ti',
            Screen: '15.6 inches Full HD',
            Weight: '2.3 Kg',
        },
    },
    {
        id: 4,
        name: 'HP Pavilion Gaming Laptop',
        description:
            'The HP Pavilion is a gaming laptop with solid performance and modern design, perfect for budget-conscious gamers.',
        brand: 'HP',
        model: 'Pavilion 15-dk0010',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fhp-pavilion-dk0010.png?alt=media&token=6f0d7c8d-0612-4ca9-9ee8-1849971ae8c4',
        rating: 4,
        videoReview: 'https://www.youtube.com/embed/dCvvugSjnZ4?si=zOMGbydgNdkB9QwY',
        tags: [],
        basePrice: 5499.99,
        promotionalPrice: 4999.99,
        lowestPrice: 4133,
        highestPrice: 7990.9,
        averagePrice: 5107.9,
        specifications: {
            highlight: 'NVIDIA GeForce GTX 1650',
            Processor: 'Intel Core i5-9300H',
            Memory: '8GB DDR4',
            Storage: '256GB SSD',
            'Graphics Card': 'NVIDIA GeForce GTX 1650',
            Screen: '15.6 inches Full HD',
            Weight: '2.25 Kg',
        },
    },
    {
        id: 5,
        name: 'ASUS TUF A15 Gaming Laptop',
        description:
            'The ASUS TUF Gaming A15 combines military-grade durability with excellent gaming performance.',
        brand: 'ASUS',
        model: 'TUF A15 FA506IV',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fasus-tuf-a15.png?alt=media&token=989d3375-f26b-4ada-a920-afa41dfdb8de',
        rating: 5,
        videoReview: 'https://www.youtube.com/embed/v-LmH_Gfnn8?si=IGQmsvb-eZyDInwV',
        tags: ['Opportunity'],
        basePrice: 7499.99,
        promotionalPrice: 6999.99,
        lowestPrice: 4133,
        highestPrice: 7990.9,
        averagePrice: 5107.9,
        specifications: {
            highlight: 'NVIDIA GeForce RTX 2060',
            Processor: 'AMD Ryzen 7 4800H',
            Memory: '16GB DDR4',
            Storage: '512GB SSD',
            'Graphics Card': 'NVIDIA GeForce RTX 2060',
            Screen: '15.6 inches Full HD 144Hz',
            Weight: '2.3 Kg',
        },
    },
    {
        id: 6,
        name: 'MSI GL65 Leopard Gaming Laptop',
        description:
            'The MSI GL65 Leopard offers superior performance with aggressive design and customizable RGB keyboard.',
        brand: 'MSI',
        model: 'GL65 Leopard 10SFK-062',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmsi-gl65.png?alt=media&token=24798828-8546-4720-bfe7-f813f4e78507',
        rating: 4,
        videoReview: 'https://www.youtube.com/embed/uT-YHREKDaE?si=Z7e2lk9G-H7-cghs',
        tags: ['Best RTX 2070'],
        basePrice: 8999.99,
        promotionalPrice: 8499.99,
        lowestPrice: 4133,
        highestPrice: 7990.9,
        averagePrice: 5107.9,
        specifications: {
            highlight: 'NVIDIA GeForce RTX 2070',
            Processor: 'Intel Core i7-10750H',
            Memory: '16GB DDR4',
            Storage: '512GB SSD',
            'Graphics Card': 'NVIDIA GeForce RTX 2070',
            Screen: '15.6 inches Full HD 144Hz',
            Weight: '2.3 Kg',
        },
    },
        {
            id: 7,
            name: 'Razer Blade 15 Gaming Laptop',
            description:
                'The Razer Blade 15 is a premium gaming laptop with an ultra-thin design and high-end hardware.',
            brand: 'Razer',
            model: 'Blade 15 Base',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Frazer-blade-15.png?alt=media&token=6e23866d-56d0-4da9-94e8-feb1b57d8fac',
            rating: 5,
            videoReview: 'https://www.youtube.com/embed/7kpreUxmHvA?si=wj5A9bw4F8zm_w_Y',
            tags: [],
            basePrice: 12499.99,
            promotionalPrice: 11999.99,
            lowestPrice: 6850,
            highestPrice: 13500,
            averagePrice: 10900.9,
            specifications: {
                highlight: 'NVIDIA GeForce RTX 2070',
                Processor: 'Intel Core i7-10750H',
                Memory: '16GB DDR4',
                Storage: '512GB SSD',
                'Graphics Card': 'NVIDIA GeForce RTX 2070',
                Display: '15.6-inch Full HD 144Hz',
                Weight: '2.1 Kg',
            },
        },
        {
            id: 8,
            name: 'Alienware m15 Gaming Laptop',
            description:
                'The Alienware m15 is a high-performance gaming laptop with a futuristic design and advanced features.',
            brand: 'Dell',
            model: 'm15 R3',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Falienware-m15.png?alt=media&token=85df89d1-3db1-4978-9581-4802b42d7c6e',
            rating: 4.5,
            videoReview: 'https://www.youtube.com/embed/OywbZPwHJBw?si=cZmqJESmXGh-D1Bw',
            tags: ['No interest'],
            basePrice: 14999.99,
            promotionalPrice: 13999.99,
            lowestPrice: 4133,
            highestPrice: 7990.9,
            averagePrice: 5107.9,
            specifications: {
                highlight: 'NVIDIA GeForce RTX 2080 Super',
                Processor: 'Intel Core i7-10875H',
                Memory: '16GB DDR4',
                Storage: '1TB SSD',
                'Graphics Card': 'NVIDIA GeForce RTX 2080 Super',
                Display: '15.6-inch Full HD 240Hz',
                Weight: '2.5 Kg',
            },
        },
        {
            id: 9,
            name: 'AMD Ryzen 7 5700X3D Processor',
            description:
                'Experience supersonic speeds with 8 cores and 16 processing threads, ready to tackle the most challenging titles. Base frequency of 3.0GHz and dynamic boost up to 4.1GHz to eliminate any lag.',
            brand: 'AMD',
            model: '100-100001503WOF',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fryzen-7-5700x3d.png?alt=media&token=62caf240-b3c6-41d9-889a-c4ca882822d9',
            rating: 4.5,
            videoReview: 'https://www.youtube.com/embed/ic8a_L15Z98&t=67s',
            tags: ['No interest', 'Best Sellers', 'Cost-Benefit'],
            basePrice: 2499.99,
            promotionalPrice: 1189.99,
            lowestPrice: 999.99,
            highestPrice: 3290.9,
            averagePrice: 1699.9,
            specifications: {
                highlight: 'AMD Ryzen 7 5700X3D',
                'CPU Core Count': 8,
                'Thread Count': 16,
                'Max Boost Clock': 4.1,
                'Base Clock': 3.0,
                'Total L2 Cache': '4MB',
                'Total L3 Cache': '96MB',
                Socket: 'AM4',
                'Max Temperature': '90°C',
                weight: '243 g',
            },
        },
        {
            id: 10,
            name: 'Intel Core i9-13900K Processor',
            description:
                'The Intel Core i9-13900K is the ideal processor for gamers and professionals who need extreme performance. Equipped with 24 cores and 32 threads, it reaches frequencies up to 5.8 GHz in turbo mode, offering unmatched performance.',
            brand: 'Intel',
            model: 'BX8071513900K',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fcore-i9-13900k.png?alt=media&token=9d185bf6-64ca-48bf-bdb7-acd0de317f09',
            rating: 4.8,
            videoReview: 'https://www.youtube.com/embed/tV-FbmLJejg',
            tags: ['Maximum Performance', 'Recommended for Gaming', 'Overclocking'],
            basePrice: 3899.99,
            promotionalPrice: 3299.99,
            lowestPrice: 2999.99,
            highestPrice: 4199.9,
            averagePrice: 3599.9,
            specifications: {
                highlight: 'Intel Core i9-13900K',
                'CPU Core Count': 24,
                'Thread Count': 32,
                'Max Boost Clock': 5.8,
                'Base Clock': 3.0,
                'Total L2 Cache': '32 MB',
                'Total L3 Cache': '36 MB',
                Socket: 'LGA 1700',
                weight: '101 g',
            },
        },
        {
            id: 11,
            name: 'AMD Ryzen 9 7950X3D Processor',
            description:
                'The AMD Ryzen 9 7950X3D processor redefines gaming and productivity performance, with 16 cores and 32 threads and a total cache of 128MB. Boost frequency of up to 5.7 GHz, ideal for intense workloads and multitasking.',
            brand: 'AMD',
            model: '100-100001700WOF',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fryzen-9-7950x3d.png?alt=media&token=74ab9ea8-1250-42b8-b653-db430969d3cf',
            rating: 4.9,
            videoReview: 'https://www.youtube.com/embed/3XFI1jhZMEU',
            tags: ['Extreme Performance', 'Flagship', 'Gamer'],
            basePrice: 5899.99,
            promotionalPrice: 4599.99,
            lowestPrice: 4199.99,
            highestPrice: 5999.9,
            averagePrice: 4999.9,
            specifications: {
                highlight: 'AMD Ryzen 9 7950X3D',
                'CPU Core Count': 16,
                'Thread Count': 32,
                'Max Boost Clock': 5.7,
                'Base Clock': 4.2,
                'Total L2 Cache': '16 MB',
                'Total L3 Cache': '128 MB',
                Socket: 'AM5',
                'Max Temperature': '95°C',
                weight: '190 g',
            },
        },
    
        {
            id: 12,
            name: 'Mechanical Gaming Keyboard Razer BlackWidow V3',
            description:
                'The Razer BlackWidow V3 is equipped with Razer Green mechanical switches for precise tactile response and satisfying auditory feedback. It features Razer Chroma RGB lighting and an aluminum frame for added durability.',
            brand: 'Razer',
            model: 'RZ03-03540100-R3U1',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fteclado-razer-blackwidow-v3.png?alt=media&token=41cf33c1-66d7-4c4f-a36f-a358d9061d29',
            rating: 4.7,
            videoReview: 'https://www.youtube.com/embed/HVPSyfIs-84',
            tags: ['Customizable RGB', 'Durability', 'Tactile Switch'],
            basePrice: 1299.99,
            promotionalPrice: 999.99,
            lowestPrice: 799.99,
            highestPrice: 1599.99,
            averagePrice: 999.99,
            specifications: {
                highlight: 'Razer Green Switch',
                'Switch Type': 'Mechanical',
                Connectivity: 'USB Cable',
                Lighting: 'Razer Chroma RGB',
                Frame: 'Aluminum',
                'Anti-Ghosting': 'Yes, N-Key Rollover',
                weight: '1130 g',
            },
        },
        {
            id: 13,
            name: 'Mechanical Gaming Keyboard Corsair K70 RGB MK.2',
            description:
                'With Cherry MX Red switches, the Corsair K70 RGB MK.2 offers a linear and silent response. Built with brushed aluminum, ideal for long gaming sessions, and dynamic RGB lighting.',
            brand: 'Corsair',
            model: 'CH-9109010-NA',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fteclado-corsair-k70.png?alt=media&token=3dbe507e-1df9-4743-b8c4-cd782cfe6c63',
            rating: 4.8,
            videoReview: 'https://www.youtube.com/embed/1ABIgPdZrkI?si=7HUrXG7JD-vkQR5_',
            tags: ['Dynamic RGB', 'Aluminum Frame', 'Silent Switch'],
            basePrice: 1799.99,
            promotionalPrice: 1349.99,
            lowestPrice: 1199.99,
            highestPrice: 2299.9,
            averagePrice: 1249.9,
            specifications: {
                highlight: 'Cherry MX Red Switch',
                'Switch Type': 'Mechanical',
                Connectivity: 'USB Cable',
                Lighting: 'Per-key RGB',
                Frame: 'Brushed Aluminum',
                'Anti-Ghosting': 'Yes, N-Key Rollover',
                weight: '1250 g',
            },
        },
        {
            id: 14,
            name: 'Mechanical Gaming Keyboard Redragon Draconic K530',
            description:
                'The Redragon Draconic K530 is a compact, wireless mechanical keyboard designed for maximum portability and performance. Equipped with Outemu Brown switches, ideal for those seeking a balance between tactile feedback and quietness, and Bluetooth connectivity.',
            brand: 'Redragon',
            model: 'K530-RGB',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fteclado-redragon-draconic-k530.png?alt=media&token=d456ac67-d742-40ed-9a99-2c3281b9a2c2',
            rating: 4.6,
            videoReview: 'https://www.youtube.com/embed/6sAqSwcjjt0',
            tags: ['Bluetooth', 'Compact', 'Portable', 'Tactile Switch'],
            basePrice: 549.99,
            promotionalPrice: 429.99,
            lowestPrice: 399.99,
            highestPrice: 599.99,
            averagePrice: 499.99,
            specifications: {
                highlight: 'Outemu Brown Switch',
                'Switch Type': 'Mechanical',
                Connectivity: 'Bluetooth 5.0 / USB-C Cable',
                Lighting: 'RGB',
                Frame: 'Reinforced ABS Plastic',
                Keys: '61 (60% Layout)',
                'Anti-Ghosting': 'Yes, N-Key Rollover',
                weight: '600 g',
            },
        },
        {
            id: 15,
            name: 'Gaming Mouse Logitech G403 Hero',
            description:
                'The Logitech G403 Hero is equipped with the HERO 25K sensor, offering maximum precision with adjustable DPI up to 25,600. Ergonomic design, lightweight frame, and adjustable weight make it ideal for those seeking comfort and high performance in games.',
            brand: 'Logitech',
            model: '910-005631',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmouse-logitech-g403-hero.png?alt=media&token=869b7dff-b08e-449f-b35c-c16d95d5cbe3',
            rating: 4.8,
            videoReview: 'https://www.youtube.com/embed/SjxHa-hv_2c',
            tags: ['Ergonomic', 'Adjustable Weight', 'HERO Sensor', 'Cost-Effective'],
            basePrice: 399.99,
            promotionalPrice: 299.99,
            lowestPrice: 279.99,
            highestPrice: 449.9,
            averagePrice: 349.99,
            specifications: {
                highlight: 'HERO 16K / 25K',
                'Maximum DPI': 25600,
                Connectivity: 'USB Cable',
                'Programmable Buttons': 6,
                Lighting: 'RGB LIGHTSYNC',
                'Response Time': '1ms',
                Frame: 'Textured ABS Plastic and Rubber',
                weight: '87 g (with adjustable 10 g weight)',
            },
        },
        {
            id: 16,
            name: 'Gaming Mouse Razer DeathAdder V2',
            description:
                'The Razer DeathAdder V2 features the Focus+ 20,000 DPI optical sensor with optical switches for faster clicks and a durability of up to 70 million clicks. Ergonomic and lightweight design with SpeedFlex cable for drag-free movements.',
            brand: 'Razer',
            model: 'RZ01-03210100-R3U1',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmouse-razer-deathadder-v2.png?alt=media&token=6b3d7cf9-334d-4950-8c66-a15d136216a6',
            rating: 4.7,
            videoReview: 'https://www.youtube.com/embed/jlmeKfzu_is',
            tags: ['Ergonomic', 'Optical Sensor', 'Optical Switches'],
            basePrice: 499.99,
            promotionalPrice: 399.99,
            lowestPrice: 349.99,
            highestPrice: 549.9,
            averagePrice: 449.99,
            specifications: {
                highlight: 'Focus+ Sensor',
                'Maximum DPI': 20000,
                Connectivity: 'USB SpeedFlex Cable',
                'Programmable Buttons': 8,
                Lighting: 'Razer Chroma RGB',
                'Response Time': '0.2ms (optical switch)',
                Frame: 'Textured ABS Plastic',
                weight: '88 g',
            },
        },
        {
            id: 17,
            name: 'Gaming Mouse HyperX Pulsefire FPS Pro',
            description:
                'The HyperX Pulsefire FPS Pro is ideal for gamers seeking precision and comfort. Equipped with the Pixart 3389 sensor with up to 16,000 DPI and high-durability Omron buttons. Customizable RGB lighting and ergonomic design.',
            brand: 'HyperX',
            model: 'HX-MC003B',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmouse-hyperxppulsefire-fps-pro.png?alt=media&token=8b0edce3-1eef-412e-be5f-bc701646b23f',
            rating: 4.5,
            videoReview: 'https://www.youtube.com/embed/sJAM6Pxa4PI',
            tags: ['High Precision', 'Pixart Sensor', 'Ergonomic'],
            basePrice: 349.99,
            promotionalPrice: 249.99,
            lowestPrice: 219.99,
            highestPrice: 399.9,
            averagePrice: 299.99,
            specifications: {
                highlight: 'Pixart 3389 Sensor',
                'Maximum DPI': 16000,
                Connectivity: 'USB Cable',
                'Programmable Buttons': 6,
                Lighting: 'RGB',
                'Response Time': '1ms',
                Frame: 'Textured ABS Plastic with Textured Sides',
                weight: '95 g',
            },
        },
        {
            id: 18,
            name: 'HyperX Cloud II Gaming Headset',
            description:
                'The HyperX Cloud II is a headset designed for maximum comfort and sound quality. It features 53mm drivers and virtual 7.1 surround sound, ideal for gamers seeking complete immersion in games.',
            brand: 'HyperX',
            model: 'KHX-HSCP-RD',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fheadset-gamer-hyperx-cloud-II.png?alt=media&token=82dce4ef-75c7-4c75-9e1a-ccf20aac1af7',
            rating: 4.8,
            videoReview: 'https://www.youtube.com/embed/BT6NFjvRNu0',
            tags: ['Comfortable', 'Surround 7.1', 'Removable Microphone'],
            basePrice: 899.99,
            promotionalPrice: 699.99,
            lowestPrice: 649.99,
            highestPrice: 949.99,
            averagePrice: 799.99,
            specifications: {
                highlight: 'Virtual Surround 7.1',
                drivers: '53mm',
                connectivity: 'USB / 3.5mm Jack',
                microphone: 'Removable with noise cancellation',
                compatibility: 'PC, PS4, Xbox One',
                weight: '320 g',
            },
        },
        {
            id: 19,
            name: 'Razer Kraken X Gaming Headset',
            description:
                'The Razer Kraken X is an ultra-lightweight headset with 7.1 surround sound and memory foam cushions for maximum comfort. Cardioid microphone and reinforced structure for durability.',
            brand: 'Razer',
            model: 'RZ04-02890100-R3U1',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fheadset-razer-kraken-x-lite.png?alt=media&token=d1219f2a-2199-4e17-9dca-5b7db5537f55',
            rating: 4.6,
            videoReview: 'https://www.youtube.com/embed/L3lW1P0rr_M',
            tags: ['Lightweight', 'Surround 7.1', 'Flexible Microphone'],
            basePrice: 299.99,
            promotionalPrice: 229.99,
            lowestPrice: 199.99,
            highestPrice: 349.99,
            averagePrice: 269.99,
            specifications: {
                highlight: 'Virtual Surround 7.1',
                drivers: '40mm',
                connectivity: '3.5mm Jack',
                microphone: 'Non-removable cardioid',
                compatibility: 'PC, PS4, Xbox One, Switch',
                weight: '250 g',
            },
        },
        {
            id: 20,
            name: 'Samsung Odyssey G7 27" Gaming Monitor',
            description:
                'The Samsung Odyssey G7 features a refresh rate of 240Hz and a response time of 1ms. With a QHD curved panel and G-Sync technology, it is ideal for gamers seeking performance and immersion.',
            brand: 'Samsung',
            model: 'LC27G75TQSNXZA',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmonitor-gamer-samsung-led-27-odyssey-curvo.png?alt=media&token=98f062fb-4c3a-4e87-895d-61ecdd7f7609',
            rating: 4.9,
            videoReview: 'https://www.youtube.com/embed/-xrNbdySG-Y',
            tags: ['240Hz', 'Curved', 'G-Sync'],
            basePrice: 3499.99,
            promotionalPrice: 2999.99,
            lowestPrice: 2799.99,
            highestPrice: 3999.99,
            averagePrice: 3299.99,
            specifications: {
                highlight: 'QHD Curved Panel',
                size: '27 inches',
                refreshRate: '240Hz',
                responseTime: '1ms',
                technology: 'QLED',
                connectivity: 'HDMI, DisplayPort, USB',
                weight: '6.5 kg',
            },
        },
        {
            id: 21,
            name: 'LG UltraGear 34" Gaming Monitor',
            description:
                'The LG UltraGear 34" is an ultra-wide monitor with WQHD resolution (3440x1440), a refresh rate of 160Hz, and G-Sync support. Ideal for those seeking a monitor for gaming and productivity.',
            brand: 'LG',
            model: '34GN850-B',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmonitor-gamer-lg-ultragear-lg-34-curvo.png?alt=media&token=7f00d9ba-f2ef-416e-bf01-0b84962e099b',
            rating: 4.7,
            videoReview: 'https://www.youtube.com/embed/YUbQODIro2k',
            tags: ['Ultra-Wide', '144Hz', 'G-Sync'],
            basePrice: 2999.99,
            promotionalPrice: 2399.99,
            lowestPrice: 2199.99,
            highestPrice: 3999.99,
            averagePrice: 2899.99,
            specifications: {
                highlight: 'WQHD Panel',
                size: '34 inches',
                refreshRate: '160Hz',
                responseTime: '1ms',
                technology: 'IPS',
                connectivity: 'HDMI, DisplayPort, USB',
                weight: '7.3 kg',
            },
        },
        {
            id: 22,
            name: 'MSI NVIDIA GeForce RTX 3060 Ventus 2X Graphics Card',
            description:
                'The RTX 3060 Ventus 2X MSI is equipped with 12GB GDDR6, offering next-gen performance for 4K gaming and Ray Tracing. It supports DLSS and advanced NVIDIA technologies for maximum performance.',
            brand: 'MSI',
            model: 'RTX 3060 Ventus',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fplaca-de-video-msi-nvidia-geforce-rtx-3060-ventus-2x-12gb.png?alt=media&token=ee112ada-6ac9-4f1c-9766-586caae1713a',
            rating: 4.9,
            videoReview: 'https://www.youtube.com/embed/a_u2HPe2Cqg',
            tags: ['4K Gaming', 'Ray Tracing', 'DLSS', 'NVIDIA', 'GeForce'],
            basePrice: 2399.99,
            promotionalPrice: 1999.99,
            lowestPrice: 1599.99,
            highestPrice: 3899.99,
            averagePrice: 2199.99,
            specifications: {
                highlight: '12GB GDDR6',
                cudaCores: 3584,
                connectivity: 'HDMI 2.1, DisplayPort 1.4a',
                tdp: '170 W',
                weight: '1.03 kg',
            },
        },
        {
            id: 23,
            name: 'AMD Radeon RX 6800 XT Graphics Card',
            description:
                'The RX 6800 XT features 16GB GDDR6 and RDNA 2 architecture, providing excellent performance in 1440p and 4K gaming. It includes support for Ray Tracing and Smart Access Memory technology for Ryzen CPUs.',
            brand: 'ASRock',
            model: '90-GA28ZZ-00UANF',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Famd-radeon-6800-xt.png?alt=media&token=f2fdddc2-fc6b-4286-8452-10add1ff37f8',
            rating: 4.7,
            videoReview: 'https://www.youtube.com/embed/ddbpej8sM9s',
            tags: ['Ray Tracing', '16GB GDDR6', 'Smart Access Memory'],
            basePrice: 6449.99,
            promotionalPrice: 5799.99,
            lowestPrice: 5499.99,
            highestPrice: 8199.99,
            averagePrice: 5999.99,
            specifications: {
                highlight: '16GB GDDR6',
                streamProcessors: 4608,
                connectivity: 'HDMI 2.1, DisplayPort 1.4',
                tdp: '300W',
                weight: '2.52 kg',
            },
        },
        {
            id: 24,
            name: 'ASUS ROG Strix Z590-E Motherboard',
            description:
                'The ASUS ROG Strix Z590-E is a high-performance motherboard with support for Intel 10th and 11th Gen processors. It features Wi-Fi 6, robust cooling, and advanced overclocking features.',
            brand: 'ASUS',
            model: 'ROG Strix Z590-E',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fplaca-mae-asus-rog-strix-z590-e-gaming.png?alt=media&token=8d4acfb0-9b08-42aa-8979-8f9e60e94e60',
            rating: 4.8,
            videoReview: 'https://www.youtube.com/embed/qAu78Pf5qhs',
            tags: ['Wi-Fi 6', 'Overclocking', 'Intel 10th/11th Gen'],
            basePrice: 1499.99,
            promotionalPrice: 1299.99,
            lowestPrice: 1199.99,
            highestPrice: 1799.99,
            averagePrice: 1399.99,
            specifications: {
                highlight: 'Support for 10th/11th Gen Intel',
                socket: 'LGA 1200',
                memory: '4 x DIMM, up to 128GB DDR4',
                connectivity: 'HDMI, DisplayPort, USB 3.2',
                weight: '1.8 kg',
            },
        },
        {
            id: 25,
            name: 'Corsair Vengeance LPX 16GB (2 x 8GB) DDR4 RAM',
            description:
                'Corsair Vengeance LPX is a high-performance DDR4 RAM with a heat spreader for optimal cooling. It features a frequency of 3200MHz and is compatible with most motherboards.',
            brand: 'Corsair',
            model: 'CMK16GX4M2B3200C16',
            image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Frandom-access-memory-corsair-vengeance-lpx-16gb.png?alt=media&token=6d4a2921-8d6c-463c-b2de-7d1235ca1f87',
            rating: 4.9,
            videoReview: 'https://www.youtube.com/embed/9fFms0foErk',
            tags: ['3200MHz', 'Overclocking', 'Low Profile'],
            basePrice: 499.99,
            promotionalPrice: 399.99,
            lowestPrice: 349.99,
            highestPrice: 599.99,
            averagePrice: 449.99,
            specifications: {
                highlight: '16GB (2 x 8GB)',
                frequency: '3200MHz',
                casLatency: '16',
                memoryType: 'DDR4',
                weight: '0.7 kg',
            },
        },              
        {
        id: 26,
        name: 'Corsair Vengeance RGB Pro 16GB RAM (2x8GB)',
        description:
            'The Corsair Vengeance RGB Pro kit offers high-level performance for gamers and content creators, with a 16GB capacity, 3200MHz frequency, and dynamic RGB lighting.',
        brand: 'Corsair',
        model: 'CMW16GX4M2C3200C16',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmemoria-corsair-vengeance-rgb-pro-16gb-2x8gb-3200mhz.png?alt=media&token=7dd6698e-8da9-4b0d-9e80-84b716da0c1a',
        rating: 4.8,
        videoReview: 'https://www.youtube.com/embed/XRkJAV6-gFw',
        tags: ['High Performance', 'RGB', 'Dual-Channel'],
        basePrice: 649.99,
        promotionalPrice: 299.99,
        lowestPrice: 299.99,
        highestPrice: 749.99,
        averagePrice: 599.99,
        specifications: {
            highlight: '16GB (2x8GB)',
            frequency: '3200MHz',
            compatibility: 'Intel and AMD',
            weight: '120 g',
        },
    },
    {
        id: 27,
        name: 'Kingston Fury Beast 32GB RAM (2x16GB)',
        description:
            'The Kingston Fury Beast is designed for users needing extra capacity. With 32GB and a 3200MHz frequency, it is ideal for advanced multitasking and heavy gaming, maintaining low latency.',
        brand: 'Kingston',
        model: 'KF436C18BBK2/32',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fmemoria-kingston-fury-beast-rgb-32gb-2x16gb-3200mhz.png?alt=media&token=533ffeb2-499b-4e72-87fb-238282dd20da',
        rating: 4.7,
        videoReview: 'https://www.youtube.com/embed/MTvBo2pSBgQ',
        tags: ['High Capacity', '3200MHz', 'Heatsink'],
        basePrice: 999.99,
        promotionalPrice: 699.99,
        lowestPrice: 549.99,
        highestPrice: 1199.99,
        averagePrice: 799.99,
        specifications: {
            highlight: '32GB (2x16GB)',
            frequency: '3200MHz',
            compatibility: 'Intel and AMD',
            weight: '150 g',
        },
    },
    {
        id: 28,
        name: 'Sony PlayStation 5 Slim',
        description:
            'The PlayStation 5 Slim offers next-gen graphics with Ray Tracing support, fast loading times with its custom SSD, and exclusive games that define the platform.',
        brand: 'Sony',
        model: 'CFI-1015A',
        image: 'https://firebasestorage.googleapis.com/v0/b/formacao-dev.appspot.com/o/lancamentos%2Fgam3rstore%2Fps5-slim.png?alt=media&token=ed2ca61f-61c6-46bf-bc75-b4155132ca97',
        rating: 4.9,
        videoReview: 'https://www.youtube.com/embed/bMFC-TM-t5E',
        tags: ['Next Gen', 'Ray Tracing', 'Exclusives'],
        basePrice: 3999.99,
        promotionalPrice: 3499.99,
        lowestPrice: 2999.99,
        highestPrice: 5999.99,
        averagePrice: 3899.99,
        specifications: {
            highlight: 'Custom SSD',
            cpu: 'AMD Ryzen Zen 2 8 cores',
            storage: '1TB SSD',
            weight: '4.05 kg',
        },
    },

]

export default products